id: P4BC81424
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: bo
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    7441980caa6146f7896443827f85c738:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    090073c0df6d434c90eb3c970abd6517:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    b4350ac57b6645d5a0790c47332654fd:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    85c5dc49e6b0430892bcf43b06df61cc:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    0a0e9162a45d4f00ac9dd98dbdd250e2:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    b12b7a793e4e43ab9bab7bccb9ee2c00:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    6778ad08fc774df2b862de8e7e06e943:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    8ce55a43afda43ec80455a11f0d77cce:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    f18265697ea84982a4b2e9323a2a38e0:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    ed0595f562d8452e9699320c2caa87ed:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    9dd8d7e74beb4b699379c61cd80d2a22:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    fe2e3033f26644bd84ac9621b82265d1:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    fadf2754a2fa4c4b959d386dbed02158:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    e17eb16c10d0449caf8b4069fece1b67:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    ca1bf63451f04c7cbb77bc3facd7e990:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    5083d433f0db47f6a316b88edb1f25a7:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    cb0b45d6f5844044a5952119741b19a4:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    518333424d9343f1ad1a3e5670209435:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    33ae3ab94dfb47cb8832b46682a1c7c0:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    36826502816847ada3ea556debce8cf3:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    840759edd88548dd8c8a7cc18ed1c5c0:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    333ea98f2c7f4365950025fb717774b5:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    3f0ee2a18cd84fee97b2e777c6bd851d:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    bbdd891035e64ea595db4dd33b7d3cfc:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    3dadeb13a8d54112b06493da2925b5ee:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    d7a3739478c5447fba7e9c18e07d9005:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    bcbf2462b1bd4b64ba3f3169de6e9921:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    371114e007cb4c9bb6718cd2dda03127:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    620892c017ed4e03905329abd3ef388f:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    f36a9c9be9994720bae7fc8a2cc9a6f6:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    a41230b4c45d4173956add91db0f467c:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    1f1cf279551c4a6db3aaa36eef0a582f:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    a50ad03fab054078b73473020879c828:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    9b72d86ba3294d11a4a206642a93aa9c:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    04deb7cd34254de6a594190ae5337598:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    3ff2962444f5415780470484d356eed4:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    26c7e95fe0d84f5899d6ada220a52554:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    fe34e0040c5d433c909f8d3b547a64e1:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    87db0cc8fbe44d9592a9391ba35612cd:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    061fbd3c1ea44a49bce41475d5ab6c95:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    0b109d60b12b4698a0596c845d912b45:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    fbc68c85ac284f8bb3e955f9995981d6:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    d3d5e492e431413cb23b548f3af26ad2:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    2c72f869dca64af9b6bd462c57145fe3:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    85f95347efc645b6a73b4f759a4ac801:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    4e7830ff7bbf471f9ac288e98bd85ffc:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    9881d35ce2c14ce9b2f0a709dfc53708:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    3d39f836b4a4498b84222a6ed5d4bd99:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    c18184895a7a465a912814e291935d7a:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    f5a12b212ca44d9384ef0442fa95defd:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    2ad27b7675fc4f33bd82d4ad55d95354:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    0c0892b8d28e47439b9c9335285acad8:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    f65bf4c811314c399d0f4f5ada4cf079:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    63bf4b36122a420cb9d817db046566e3:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    4cda0dd0eb8e41aaad201c1294000966:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    b4809eff68cc4ccb984a4075b99e0d1d:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    364dade3ed5d488589d4e0045efde863:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    9e77c8a584a7456da3f3eef16e8600ea:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    c0f05fd20867495fa6565c2f916605e8:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    308c2ed2b23a4b2b9f325e3c6139e902:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    0ecee124a9214374a891ad79325a193e:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    32aa1fe8074f4e41ae214751ff873208:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    283f79c20167443baf78623d496c1628:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    bce0910345714e1ab9c89ff7f5850d3f:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    94bec9e8ead04a2d982006626680321a:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    4e66134a0b23480cb5d81733c76ff6d9:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    97ec39e45ea54dba9baacbd059cf57a5:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    81f4a1020c344597ac46d50734444614:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    8cb086c7206c4f858bdc47f0b2cd73cf:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    77170baf3e814fec9f57b8ffbe9d6881:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    1d5edc6b6ea84d9e93a0fa1597b4b921:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    e2eefbca7e594125be7b39630739cb70:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    af75d58972574ae8a70cf694c8f4023f:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    231f445248ff45479af9e971b84d7c88:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    8786b7346090402395290db8d90efb0f:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    1372b6d6bfe6407088abb96f97c39840:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    2f8a7db4cbf344569fe07b56e874b135:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    d1cabd2168d54c3da2485c60acc1e922:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    59d56cc7b3f946b2b10a3cae35e982b1:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.062204'
last_modified_at: '2022-03-01T03:50:02.062207'
statistics:
  total_words: 44270
  total_non_words: 3377
quality:
  non_words_ratio: 0.08
